# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices = {
    cryptroot.device = "/dev/disk/by-uuid/abdbb2f8-2dc3-45a0-96e8-433039e20c3d";
    cryptswap.device = "/dev/disk/by-uuid/2c40f156-cc00-4f9f-a0c4-7360fc0ad9bd";
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/bf102f28-af70-4fb1-8f69-cdabc183c00c";
      fsType = "ext4";
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/7786-F132";
      fsType = "vfat";
    };
  };

  swapDevices = [{ device = "/dev/disk/by-uuid/74f18c93-28a7-48e6-a728-f594ceebd9a6"; }];

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
